//
// Created by steve on 3/3/19.
//

#ifndef PRACTICEVISUALPOSITIONING_FEATUREMANAGER_H
#define PRACTICEVISUALPOSITIONING_FEATUREMANAGER_H


class FeatureManager {

};


#endif //PRACTICEVISUALPOSITIONING_FEATUREMANAGER_H
