//
// Created by steve on 3/3/19.
//

#ifndef PRACTICEVISUALPOSITIONING_FRONTENDOPTIMIZER_H
#define PRACTICEVISUALPOSITIONING_FRONTENDOPTIMIZER_H


class FrontEndOptimizer {

};


#endif //PRACTICEVISUALPOSITIONING_FRONTENDOPTIMIZER_H
