//
// Created by steve on 3/10/19.
//

#ifndef PRACTICEVISUALPOSITIONING_SFMFEATUREMANAGER_H
#define PRACTICEVISUALPOSITIONING_SFMFEATUREMANAGER_H


class SFMFeatureManager {

};


#endif //PRACTICEVISUALPOSITIONING_SFMFEATUREMANAGER_H
