//
// Created by steve on 4/2/19.
//

#ifndef PRACTICEVISUALPOSITIONING_SIMPLEKPPRIORERROR_H
#define PRACTICEVISUALPOSITIONING_SIMPLEKPPRIORERROR_H


class SimpleKPPriorError {

};


#endif //PRACTICEVISUALPOSITIONING_SIMPLEKPPRIORERROR_H
