//
// Created by steve on 3/27/19.
//

#ifndef PRACTICEVISUALPOSITIONING_SIMPLEREPROJECTIONERROR_H
#define PRACTICEVISUALPOSITIONING_SIMPLEREPROJECTIONERROR_H


class SimpleReprojectionError {

};


#endif //PRACTICEVISUALPOSITIONING_SIMPLEREPROJECTIONERROR_H
