//
// Created by steve on 3/25/19.
//

#ifndef PRACTICEVISUALPOSITIONING_STEREOODOMETRYSERVER_H
#define PRACTICEVISUALPOSITIONING_STEREOODOMETRYSERVER_H


class StereoOdometryServer {

};


#endif //PRACTICEVISUALPOSITIONING_STEREOODOMETRYSERVER_H
