//
// Created by steve on 3/25/19.
//

#ifndef PRACTICEVISUALPOSITIONING_STEREOFEATUREMANAGER_H
#define PRACTICEVISUALPOSITIONING_STEREOFEATUREMANAGER_H


class StereoFeatureManager {

};


#endif //PRACTICEVISUALPOSITIONING_STEREOFEATUREMANAGER_H
