//
// Created by steve on 3/25/19.
//

#ifndef PRACTICEVISUALPOSITIONING_STEREOFEATURETRACKER_H
#define PRACTICEVISUALPOSITIONING_STEREOFEATURETRACKER_H


class StereoFeatureTracker {

};


#endif //PRACTICEVISUALPOSITIONING_STEREOFEATURETRACKER_H
