//
// Created by steve on 3/25/19.
//

#ifndef PRACTICEVISUALPOSITIONING_STEREOFEATURETRACKER_H
#define PRACTICEVISUALPOSITIONING_STEREOFEATURETRACKER_H

#include <opencv2/opencv.hpp>

class StereoFeatureTracker {
public:

};


#endif //PRACTICEVISUALPOSITIONING_STEREOFEATURETRACKER_H
